name: nlpbi
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - blas=1.0
  - brotli-python=1.0.9
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - cpuonly=2.0
  - cpython=3.9.20
  - debugpy=1.8.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.13.1
  - freetype=2.12.1
  - giflib=5.2.2
  - gmpy2=2.1.2
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lcms2=2.12
  - lerc=3.0
  - libabseil=20240722.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.17
  - libhwloc=2.9.0
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libpng=1.6.44
  - libprotobuf=5.27.5
  - libsentencepiece=0.2.0
  - libsodium=1.0.20
  - libsqlite=3.45.3
  - libtiff=4.5.0
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - pthreads-win32=2.9.1
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.9.20
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pytorch=2.5.0
  - pytorch-mutex=1.0
  - pywin32=307
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - requests=2.32.3
  - sentencepiece=0.2.0
  - sentencepiece-python=0.2.0
  - sentencepiece-spm=0.2.0
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tk=8.6.13
  - torchaudio=2.5.0
  - torchvision=0.20.0
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - urllib3=2.2.3
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - accelerate==1.0.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asgiref==3.8.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==24.2.0
      - babel==2.16.0
      - backoff==2.2.1
      - bcrypt==4.2.1
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - build==1.2.2.post1
      - cachetools==5.5.0
      - chroma-hnswlib==0.7.6
      - chromadb==0.5.23
      - click==8.1.7
      - coloredlogs==15.0.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==3.0.1
      - defusedxml==0.7.1
      - deprecated==1.2.15
      - dill==0.3.8
      - distro==1.9.0
      - dnspython==2.7.0
      - durationpy==0.9
      - email-validator==2.2.0
      - et-xmlfile==1.1.0
      - fastapi==0.115.5
      - fastapi-cli==0.0.5
      - fastjsonschema==2.20.0
      - ffmpy==0.4.0
      - flatbuffers==24.3.25
      - fonttools==4.55.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - google-auth==2.37.0
      - googleapis-common-protos==1.66.0
      - gradio==4.44.1
      - gradio-client==1.3.0
      - greenlet==3.1.1
      - grpcio==1.68.1
      - h11==0.14.0
      - httpcore==1.0.6
      - httptools==0.6.4
      - httpx==0.27.2
      - httpx-sse==0.4.0
      - huggingface-hub==0.25.2
      - humanfriendly==10.0
      - importlib-resources==6.4.5
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jiter==0.7.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - kubernetes==31.0.0
      - langchain==0.3.9
      - langchain-community==0.3.9
      - langchain-core==0.3.29
      - langchain-openai==0.2.9
      - langchain-text-splitters==0.3.2
      - langgraph==0.2.62
      - langgraph-checkpoint==2.0.5
      - langgraph-sdk==0.1.51
      - langsmith==0.1.144
      - markdown-it-py==3.0.0
      - marshmallow==3.23.1
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mistune==3.0.2
      - mmh3==5.0.1
      - monotonic==1.6
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - oauthlib==3.2.2
      - onnxruntime==1.19.2
      - openai==1.55.0
      - openpyxl==3.1.5
      - opentelemetry-api==1.29.0
      - opentelemetry-exporter-otlp-proto-common==1.29.0
      - opentelemetry-exporter-otlp-proto-grpc==1.29.0
      - opentelemetry-instrumentation==0.50b0
      - opentelemetry-instrumentation-asgi==0.50b0
      - opentelemetry-instrumentation-fastapi==0.50b0
      - opentelemetry-proto==1.29.0
      - opentelemetry-sdk==1.29.0
      - opentelemetry-semantic-conventions==0.50b0
      - opentelemetry-util-http==0.50b0
      - orjson==3.10.11
      - overrides==7.7.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - pillow==10.4.0
      - posthog==3.7.4
      - prometheus-client==0.21.0
      - propcache==0.2.0
      - protobuf==5.29.2
      - psycopg2==2.9.10
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.0
      - pydantic-core==2.27.0
      - pydantic-extra-types==2.10.0
      - pydantic-settings==2.6.1
      - pydub==0.25.1
      - pygame==2.6.1
      - pyparsing==3.2.0
      - pypdf==5.1.0
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.17
      - pytz==2024.2
      - pywinpty==2.0.13
      - referencing==0.35.1
      - regex==2024.9.11
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.20.0
      - rsa==4.9
      - ruff==0.7.4
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.36
      - starlette==0.41.3
      - sympy==1.13.1
      - tenacity==9.0.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tiktoken==0.8.0
      - tinycss2==1.3.0
      - tokenizers==0.20.1
      - tomli==2.0.2
      - tomlkit==0.12.0
      - tqdm==4.66.5
      - transformers==4.45.2
      - typer==0.13.1
      - types-python-dateutil==2.9.0.20241003
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - ujson==5.10.0
      - uri-template==1.3.0
      - uvicorn==0.32.1
      - watchfiles==0.24.0
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - widgetsnbextension==4.0.13
      - wrapt==1.17.0
      - xxhash==3.5.0
      - yarl==1.15.4
